version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: pim_mysql
    environment:
      MYSQL_ROOT_PASSWORD: newrootpassword
      MYSQL_DATABASE: pim
      MYSQL_USER: newuser
      MYSQL_PASSWORD: newpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: